# NOTE: the values in this secret are provided as working manifest example and are not the values
# used during an install. New values will be generated as part of `argocd install`
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
type: Opaque
stringData:
  # bcrypt hash of the string "password"
  admin.password: ""
  # random server signature key for session validation
  server.secretkey: ""

  # The following keys hold the shared secret for authenticating GitHub/GitLab/BitBucket webhook
  # events. To enable webhooks, configure one or more of the following keys with the shared git
  # provider webhook secret. The payload URL configured in the git provider should use the 
  # /api/webhook endpoint of your ArgoCD instance (e.g. https://argocd.example.com/api/webhook)
  github.webhook.secret: ""
  gitlab.webhook.secret: ""
  bitbucket.webhook.uuid: your-bitbucket-uuid

  # the following of user defined keys which are referenced in the example argocd-cm configmap
  # as pat of SSO configuration.
  dex.github.clientSecret: ""
  dex.acme.clientSecret: ""
  dex.okta.clientSecret: ""
